In [1]:
FAMILY_MAP = {
    "Gaussian": "GaussianCopula",
    "Bernoulli": "BernoulliCopula",
    "NegBin": "NegBinCopula",
    "NegBinIRLS": "NegBinIRLSCopula",
    "Poisson": "PoissonCopula",
    "pNMF": "PositiveNMF",
    "ZeroInflatedNegBin": "ZeroInflatedNegBinCopula",
    "ZeroInflatedPoisson": "ZeroInflatedPoissonCopula"
}

In [2]:
import importlib
import random

def make_formulas(formulas: dict) -> dict:
    formula_strs = {}

    # loop over model parameters
    for param, variables in formulas.items():
        terms = []

        # loop over predictors for that parameter
        for var in variables:
            if "transform" in var and var["transform"].get("type") == "spline":
                terms.append(f"bs({var['variable']}, df={var['transform']['df']})")
            else:
                terms.append(var['variable'])
        formula_strs[f"{param}_formula"] = "~ " + " + ".join(terms) if terms else "~ 1"

    return formula_strs

def generate_data(state):
    # prepare the formula and simulator type
    class_name = FAMILY_MAP[state["family"]]
    simulator_class = getattr(importlib.import_module("scdesigner.simulators"), class_name)
    fmla = make_formulas(state["formulas"])

    # fit the simulator
    simulator = simulator_class(**fmla)
    simulator.fit(state["template"], max_epochs=25)

    # sample new data
    n_cells = state["n_cells"] or len(state["template"])
    ix = random.choices(range(len(state["template"])), k=n_cells)
    new_data = simulator.sample(state["template"].obs.iloc[ix, :])

    return simulator.parameters, new_data

Here is a version of a negative binomial model where we use cell_type as a predictor and don't have any change as a function of pseudotime.

In [3]:
from scdesigner.datasets import pancreas

formulas = {
    "mean": [{"variable": "cell_type"}],
    "dispersion": [{"variable": "cell_type"}],
    "copula": []
}

example_sce = pancreas()
state = {"template": example_sce, "family": "NegBin", "formulas": formulas, "n_cells": None}
parameters, adata_sim = generate_data(state)

Epoch 25/25, Loss: 1.9644, Val Loss: 1.9669

Estimating copula correlation: 100%|██████████| 3/3 [00:00<00:00, 18.12it/s]

Here are the coefficients for each gene's negative binomial model.

In [4]:
parameters["marginal"]["mean"]

,Pyy,Iapp,Chgb,Rbp4,Spp1,Chga,Cck,Ins1,Nnat,Ins2,...,Nkx6-1,Fxyd3,Hn1,Smarcd2,Pdia6,Ffar2,Hes6,Serpinh1,Npy,1110012L19Rik
Intercept,0.056393,-0.913212,-1.434003,-0.371312,4.194845,-2.053644,-1.904621,-1.275848,-1.547781,-2.636792,...,0.478958,-0.248252,1.503538,0.253186,1.158546,-0.605932,0.406455,1.610021,-4.507418,-0.713368
cell_type[T.Ngn3 high EP],-0.339077,-0.154239,1.118734,-0.881085,-1.575483,2.066646,4.854985,-0.410084,1.006965,-0.193357,...,0.687333,0.891716,0.340465,1.210708,-0.411229,1.172308,1.272929,-0.248277,-0.091334,1.328641
cell_type[T.Pre-endocrine],3.050847,0.409684,5.192988,2.746677,-5.625076,5.042534,4.604670,-0.320688,1.032740,-0.026869,...,0.767221,1.301734,-0.597094,0.081594,-1.151457,1.760671,0.142529,-1.836462,-0.324963,1.572527
cell_type[T.Beta],4.887130,5.907669,4.737278,4.140733,-5.543490,4.952433,2.914708,5.442261,5.048255,6.070582,...,1.024900,0.887283,-1.000395,-1.103323,0.740540,0.999349,-0.187658,-2.099929,4.552769,-0.011510

Here's the estimated copula covariance matrix.

In [5]:
parameters["copula"]["Intercept"]

,Pyy,Iapp,Chgb,Rbp4,Spp1,Chga,Cck,Ins1,Nnat,Ins2,...,Nkx6-1,Fxyd3,Hn1,Smarcd2,Pdia6,Ffar2,Hes6,Serpinh1,Npy,1110012L19Rik
Pyy,1.000000,0.126321,-0.085389,0.346678,0.000623,-0.035735,-0.010717,0.005677,-0.000792,0.021791,...,-0.102327,0.025770,-0.023785,-0.064202,0.080200,-0.034890,-0.039160,0.011005,0.040048,-0.037759
Iapp,0.126321,1.000000,-0.067082,0.088181,0.032738,-0.042089,-0.006166,0.217170,0.208065,0.263073,...,0.076002,-0.030533,-0.000354,-0.047102,0.216239,-0.075577,-0.008646,0.010124,0.125227,-0.043758
Chgb,-0.085389,-0.067082,1.000000,-0.026880,-0.066219,0.268039,0.035865,-0.088098,-0.065218,-0.064559,...,0.139615,0.110847,-0.049165,-0.081802,-0.061537,0.129175,-0.001272,-0.106894,-0.023548,0.066967
Rbp4,0.346678,0.088181,-0.026880,1.000000,0.015750,-0.011822,-0.079656,0.026787,0.001032,0.028769,...,-0.109846,0.069343,-0.079439,-0.110310,0.102679,-0.028936,-0.082720,-0.019946,0.015296,-0.083640
Spp1,0.000623,0.032738,-0.066219,0.015750,1.000000,-0.101596,-0.314775,0.027572,-0.014754,0.039638,...,-0.145158,-0.122502,-0.153297,-0.119933,0.181906,-0.063257,-0.036806,0.132208,0.065363,-0.150834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ffar2,-0.034890,-0.075577,0.129175,-0.028936,-0.063257,0.075138,0.090956,-0.068157,-0.077033,-0.040072,...,0.063466,0.118909,0.049447,0.063053,-0.038642,1.000000,0.053995,-0.038933,-0.067653,0.079968
Hes6,-0.039160,-0.008646,-0.001272,-0.082720,-0.036806,-0.027054,0.099431,-0.015931,0.029630,0.043839,...,0.090323,0.046832,0.237574,0.208088,0.013306,0.053995,1.000000,0.125868,-0.023937,0.099290
Serpinh1,0.011005,0.010124,-0.106894,-0.019946,0.132208,-0.085992,-0.029926,0.019398,0.027503,0.018689,...,-0.014499,-0.035117,0.115858,0.135863,0.162780,-0.038933,0.125868,1.000000,0.007564,0.012198
Npy,0.040048,0.125227,-0.023548,0.015296,0.065363,-0.002341,0.010873,0.136334,0.156191,0.140886,...,0.047979,-0.043304,0.007188,-0.012434,0.133251,-0.067653,-0.023937,0.007564,1.000000,-0.010460
1110012L19Rik,-0.037759,-0.043758,0.066967,-0.083640,-0.150834,0.106428,0.234575,-0.030985,0.034631,-0.006005,...,0.107616,0.146914,0.145500,0.107957,-0.080769,0.079968,0.099290,0.012198,-0.010460,1.000000

We can let the copula correlations depend on the cell type.

In [6]:
formulas["copula"] = [{"variable": "cell_type"}]
state["formulas"] = formulas
parameters, _ = generate_data(state)

# covariance matrix for this cell type
parameters["copula"]["cell_type[T.Beta]"]

Epoch 25/25, Loss: 1.9644, Val Loss: 1.9669

Estimating copula correlation: 100%|██████████| 3/3 [00:00<00:00, 24.25it/s]

,Pyy,Iapp,Chgb,Rbp4,Spp1,Chga,Cck,Ins1,Nnat,Ins2,...,Nkx6-1,Fxyd3,Hn1,Smarcd2,Pdia6,Ffar2,Hes6,Serpinh1,Npy,1110012L19Rik
Pyy,1.000000,0.207740,-0.098843,0.293167,0.001171,0.018371,0.207174,0.026863,0.055896,0.008526,...,-0.036037,0.025904,0.037427,-0.044273,0.074343,0.088801,0.014141,0.067883,-0.084031,0.011012
Iapp,0.207740,1.000000,-0.363959,0.160456,0.119042,-0.145963,0.035572,0.630846,0.733933,0.696559,...,0.279717,-0.114319,0.065675,-0.051819,0.594138,-0.189291,-0.007132,0.093320,0.363619,0.044982
Chgb,-0.098843,-0.363959,1.000000,-0.056308,-0.111537,0.297899,0.179310,-0.302399,-0.290686,-0.309793,...,0.010352,0.231488,0.086213,0.007014,-0.158622,0.207239,0.099362,-0.000488,-0.193257,0.001178
Rbp4,0.293167,0.160456,-0.056308,1.000000,-0.014920,0.106800,0.195990,-0.053400,0.120484,-0.010274,...,-0.031764,0.243617,0.120160,0.028258,0.150326,0.067519,0.027826,0.034498,-0.085550,0.085892
Spp1,0.001171,0.119042,-0.111537,-0.014920,1.000000,0.013465,-0.073730,0.125713,0.135131,0.155592,...,0.108096,-0.029671,0.022053,-0.005206,0.085419,-0.094031,0.036239,0.036901,0.114982,0.027449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ffar2,0.088801,-0.189291,0.207239,0.067519,-0.094031,0.129450,0.084995,-0.159847,-0.126356,-0.145581,...,0.008929,0.138065,0.055173,0.070706,-0.095036,1.000000,0.079395,0.021792,-0.112455,0.063407
Hes6,0.014141,-0.007132,0.099362,0.027826,0.036239,0.058406,0.102845,-0.071941,-0.073944,-0.073600,...,0.120978,0.067097,0.118050,0.116716,-0.038314,0.079395,1.000000,0.088120,-0.064679,0.170705
Serpinh1,0.067883,0.093320,-0.000488,0.034498,0.036901,0.061049,0.064859,0.097595,0.080651,0.170330,...,0.096081,0.057236,0.156663,0.087891,0.160695,0.021792,0.088120,1.000000,0.116181,0.082233
Npy,-0.084031,0.363619,-0.193257,-0.085550,0.114982,-0.077512,-0.011946,0.432437,0.436257,0.471613,...,0.168771,-0.098465,0.023193,0.043234,0.308148,-0.112455,-0.064679,0.116181,1.000000,-0.032519
1110012L19Rik,0.011012,0.044982,0.001178,0.085892,0.027449,0.037837,0.104985,-0.002627,-0.013956,0.008963,...,0.094635,0.050890,0.086180,0.084121,0.033872,0.063407,0.170705,0.082233,-0.032519,1.000000

We can allow the means and dispersions to vary smoothly over pseudotime by using spline transformations in the predictors. The `make_formulas` function transforms the object below into strings like `~ bs(pseudotime, df=8)`. I'm breaking that string down into this structure because I think it might map more easily onto user inputs (e.g., selecting variables from a list populated by the `obs` field of the anndata object, then clicking whether a spline should be used). But internally we just need the formula strings -- let me know if there's a more natural data structure from a UI perspective.

In [7]:
formulas = {
    "mean": [{"variable": "pseudotime", "transform": {"type": "spline", "df": 8}}],
    "dispersion": [{"variable": "pseudotime", "transform": {"type": "spline", "df": 3}}],
    "copula": [{"variable": "cell_type"}]
}

state = {"template": example_sce, "family": "NegBin", "formulas": formulas, "n_cells": None}
generate_data(state)

Epoch 25/25, Loss: 1.8605, Val Loss: 1.8677

Estimating copula correlation: 100%|██████████| 3/3 [00:00<00:00, 24.48it/s]

({'marginal': {'mean':                               Pyy      Iapp      Chgb      Rbp4      Spp1  \
   Intercept               -0.005292 -0.967646 -1.726450 -0.056083  4.388359
   bs(pseudotime, df=8)[1] -0.225362 -0.343137  0.024613 -0.549686 -0.446189
   bs(pseudotime, df=8)[2] -0.325008  0.731518 -0.899952 -0.933407  0.734141
   bs(pseudotime, df=8)[3] -0.468245 -1.007560 -0.238769 -1.699383 -5.589237
   bs(pseudotime, df=8)[4]  0.495997  1.066375  6.016636  0.307727 -7.015829
   bs(pseudotime, df=8)[5]  4.303521 -1.121429  5.843637  3.422356 -5.144053
   bs(pseudotime, df=8)[6]  5.316972  7.132685  4.903174  4.169022 -6.636533
   bs(pseudotime, df=8)[7]  5.392619  5.970867  4.848661  4.031403 -5.415489
   bs(pseudotime, df=8)[8]  4.449085  7.508679  3.878354  3.405123 -5.226408

                                Chga       Cck      Ins1      Nnat      Ins2  \
   Intercept               -4.491948 -1.729480 -0.883534 -1.629171 -2.281118
   bs(pseudotime, df=8)[1]  5.076053 -1.202516 -1.205205 -0.196268 -1.293907
   bs(pseudotime, df=8)[2] -3.653638  0.844543 -0.139211  0.079594  0.702932
   bs(pseudotime, df=8)[3]  4.697207  6.181507 -1.594140  1.660029 -1.642746
   bs(pseudotime, df=8)[4]  8.055101  4.975495  0.373194  1.419617  1.276215
   bs(pseudotime, df=8)[5]  7.513555  3.599574 -2.616814  0.128241 -3.073697
   bs(pseudotime, df=8)[6]  7.533102  2.013260  2.731794  5.026532  4.688415
   bs(pseudotime, df=8)[7]  7.053191  3.223205  4.332917  5.600252  6.146086
   bs(pseudotime, df=8)[8]  7.120775  2.067229  8.439963  6.511631  7.754392

                            ...    Nkx6-1     Fxyd3       Hn1   Smarcd2  \
   Intercept                ...  0.630311 -0.371049  1.591818  0.249854
   bs(pseudotime, df=8)[1]  ... -0.462435  0.399579 -0.530733 -0.442675
   bs(pseudotime, df=8)[2]  ... -0.251036 -0.908527 -0.028778  1.552714
   bs(pseudotime, df=8)[3]  ...  1.018008  1.687736  0.802366  1.504897
   bs(pseudotime, df=8)[4]  ...  0.693160  1.653070 -0.354930  0.539313
   bs(pseudotime, df=8)[5]  ...  0.537962  1.246773 -1.420616 -0.771660
   bs(pseudotime, df=8)[6]  ...  0.654276  1.149976 -0.955143 -1.342579
   bs(pseudotime, df=8)[7]  ...  1.093878  1.087872 -1.027577 -0.931373
   bs(pseudotime, df=8)[8]  ...  1.238293  0.025450 -1.256344 -1.600301

                               Pdia6     Ffar2      Hes6  Serpinh1       Npy  \
   Intercept                1.207600 -1.837805 -0.539821  1.839619 -5.194612
   bs(pseudotime, df=8)[1] -0.143722  1.963029  1.046605 -0.487817  1.304230
   bs(pseudotime, df=8)[2]  0.203965  2.390919  2.841900 -0.058386 -0.475510
   bs(pseudotime, df=8)[3] -0.608042  2.106831  2.371736 -0.336177  1.613252
   bs(pseudotime, df=8)[4] -1.912059  3.564882  1.239717 -1.938081 -1.788913
   bs(pseudotime, df=8)[5] -1.137403  2.787577  0.637839 -2.818730  3.788952
   bs(pseudotime, df=8)[6]  0.619023  2.234829  0.805860 -2.275657 -6.808186
   bs(pseudotime, df=8)[7]  0.908611  1.941000  0.877952 -2.462800  8.204665
   bs(pseudotime, df=8)[8]  1.722870  1.622984  0.279376 -1.787304  8.906542

                            1110012L19Rik
   Intercept                    -0.966103
   bs(pseudotime, df=8)[1]       0.537227
   bs(pseudotime, df=8)[2]      -0.646306
   bs(pseudotime, df=8)[3]       2.137259
   bs(pseudotime, df=8)[4]       2.774238
   bs(pseudotime, df=8)[5]       1.066798
   bs(pseudotime, df=8)[6]      -0.368078
   bs(pseudotime, df=8)[7]       0.590284
   bs(pseudotime, df=8)[8]      -0.344915

   [9 rows x 100 columns],
   'dispersion':                               Pyy      Iapp      Chgb      Rbp4      Spp1  \
   Intercept               -0.766796 -0.672036  0.009502  0.296809  1.228963
   bs(pseudotime, df=3)[1] -0.217402  0.204323 -0.230225 -0.228284 -0.231311
   bs(pseudotime, df=3)[2] -0.215084  0.224035 -0.215078 -0.218838 -0.240189
   bs(pseudotime, df=3)[3]  0.062821  0.239645  0.201980  0.244549 -0.216958

                                Chga       Cck      Ins1      Nnat      Ins2  \
   Intercept                0.344281  0.572235 -1.393546  1.017914  1.003399
   bs(pseudotime, df=3)[1] -0.215453 -0.218387  0.238408 -0.245551 -0.227864
   bs(pseudotime, df=3)[2] -0.142216 -0.226429  0.216174 -0.240982 -0.223753
   bs(pseudotime, df=3)[3]  0.261325 -0.236820  0.233903 -0.225000 -0.202684

                            ...    Nkx6-1     Fxyd3       Hn1   Smarcd2  \
   Intercept                ...  1.137142  0.499507  1.166429  2.340576
   bs(pseudotime, df=3)[1]  ... -0.195822  0.068574  0.202301  0.187756
   bs(pseudotime, df=3)[2]  ... -0.203737  0.135622  0.215669  0.027568
   bs(pseudotime, df=3)[3]  ...  0.269301 -0.206164  0.223714 -0.087937

                               Pdia6     Ffar2      Hes6  Serpinh1       Npy  \
   Intercept                1.659087  0.708345  1.536280  2.106755 -0.403807
   bs(pseudotime, df=3)[1] -0.171496 -0.004930  0.027823  0.084701 -0.247370
   bs(pseudotime, df=3)[2] -0.157699 -0.003190 -0.109372 -0.244410 -0.232401
   bs(pseudotime, df=3)[3]  0.126729 -0.043004  0.129514 -0.242494 -0.225443

                            1110012L19Rik
   Intercept                     0.472089
   bs(pseudotime, df=3)[1]      -0.018211
   bs(pseudotime, df=3)[2]      -0.037158
   bs(pseudotime, df=3)[3]       0.167600

   [4 rows x 100 columns]},
  'copula': {'Intercept':                     Pyy      Iapp      Chgb      Rbp4      Spp1      Chga  \
   Pyy            1.000000  0.068996 -0.141911  0.214829  0.022670 -0.056313
   Iapp           0.068996  1.000000 -0.000373  0.016737 -0.008008  0.026745
   Chgb          -0.141911 -0.000373  1.000000 -0.118040  0.006425  0.116747
   Rbp4           0.214829  0.016737 -0.118040  1.000000  0.012275 -0.033542
   Spp1           0.022670 -0.008008  0.006425  0.012275  1.000000  0.027568
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2         -0.002170 -0.001524  0.058649  0.005879  0.023148  0.028775
   Hes6           0.013594  0.046425  0.093529  0.020845  0.045780  0.061611
   Serpinh1       0.049950 -0.046443  0.049008  0.045290  0.021291  0.047591
   Npy           -0.038831  0.030018  0.017297  0.001535  0.019196 -0.030297
   1110012L19Rik -0.002641 -0.011944  0.013495  0.044700  0.050509  0.029612

                       Cck      Ins1      Nnat      Ins2  ...    Nkx6-1  \
   Pyy            0.092466  0.042828 -0.016279 -0.020044  ... -0.107363
   Iapp           0.054666  0.060550  0.036979  0.041277  ...  0.021191
   Chgb           0.073133 -0.028604  0.041203 -0.000378  ...  0.198833
   Rbp4           0.086560  0.008622  0.019346  0.011785  ... -0.086415
   Spp1           0.021272  0.023548  0.036589  0.007273  ...  0.058117
   ...                 ...       ...       ...       ...  ...       ...
   Ffar2          0.020541  0.012540  0.027196  0.014260  ...  0.051929
   Hes6           0.036889 -0.001858  0.042863  0.004298  ...  0.082732
   Serpinh1      -0.005651  0.054679  0.048498  0.012399  ...  0.022308
   Npy            0.045470  0.013062  0.076270  0.056491  ...  0.006695
   1110012L19Rik  0.062143 -0.002950  0.018829  0.032161  ...  0.027913

                     Fxyd3       Hn1   Smarcd2     Pdia6     Ffar2      Hes6  \
   Pyy            0.019724  0.041704  0.026067  0.033942 -0.002170  0.013594
   Iapp           0.035755  0.058024  0.018922 -0.008361 -0.001524  0.046425
   Chgb           0.066307  0.059026  0.011717  0.071627  0.058649  0.093529
   Rbp4           0.067650  0.048562  0.009031  0.092030  0.005879  0.020845
   Spp1           0.034814  0.040218  0.026086  0.091451  0.023148  0.045780
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.072678  0.014612  0.052822  0.067763  1.000000  0.014331
   Hes6           0.040232  0.133412  0.095823  0.070299  0.014331  1.000000
   Serpinh1       0.014227  0.091340  0.079949  0.116217  0.000910  0.082422
   Npy           -0.024967 -0.009142  0.004651 -0.010340 -0.006680 -0.015024
   1110012L19Rik  0.026436  0.055480  0.040810  0.044829  0.011703  0.077075

                  Serpinh1       Npy  1110012L19Rik
   Pyy            0.049950 -0.038831      -0.002641
   Iapp          -0.046443  0.030018      -0.011944
   Chgb           0.049008  0.017297       0.013495
   Rbp4           0.045290  0.001535       0.044700
   Spp1           0.021291  0.019196       0.050509
   ...                 ...       ...            ...
   Ffar2          0.000910 -0.006680       0.011703
   Hes6           0.082422 -0.015024       0.077075
   Serpinh1       1.000000  0.016168       0.044506
   Npy            0.016168  1.000000      -0.037948
   1110012L19Rik  0.044506 -0.037948       1.000000

   [100 rows x 100 columns],
   'cell_type[T.Ngn3 high EP]':                     Pyy      Iapp      Chgb      Rbp4      Spp1      Chga  \
   Pyy            1.000000  0.059736  0.034820  0.014185 -0.001718 -0.019725
   Iapp           0.059736  1.000000  0.064711 -0.024634 -0.016953  0.025885
   Chgb           0.034820  0.064711  1.000000 -0.025879  0.032632 -0.044263
   Rbp4           0.014185 -0.024634 -0.025879  1.000000  0.011390 -0.012541
   Spp1          -0.001718 -0.016953  0.032632  0.011390  1.000000  0.063944
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.047301 -0.047000 -0.060338  0.041763  0.079130 -0.012475
   Hes6          -0.030007  0.028216  0.058838  0.016814  0.062653  0.058724
   Serpinh1       0.038895 -0.098719  0.133066 -0.015862  0.080068  0.000829
   Npy           -0.049184  0.103004 -0.001308 -0.015502 -0.005254 -0.033702
   1110012L19Rik -0.016626 -0.111322 -0.029256  0.020484  0.035398  0.003628

                       Cck      Ins1      Nnat      Ins2  ...    Nkx6-1  \
   Pyy            0.054156  0.095297  0.092540 -0.016255  ...  0.014772
   Iapp          -0.011044  0.006457  0.042033  0.053926  ... -0.008373
   Chgb           0.021402 -0.014142 -0.008738 -0.041045  ... -0.001691
   Rbp4          -0.006613 -0.032458 -0.005884  0.002971  ...  0.017415
   Spp1           0.025323 -0.012342 -0.008727 -0.039640  ...  0.071599
   ...                 ...       ...       ...       ...  ...       ...
   Ffar2         -0.011185  0.023101 -0.001444 -0.028812  ... -0.027882
   Hes6           0.069004 -0.046143  0.034381 -0.008251  ...  0.067956
   Serpinh1      -0.004750  0.010134  0.039548 -0.041577  ...  0.041528
   Npy            0.050251 -0.024484  0.011361  0.035334  ... -0.035926
   1110012L19Rik -0.024699 -0.015935 -0.009268  0.044742  ... -0.008417

                     Fxyd3       Hn1   Smarcd2     Pdia6     Ffar2      Hes6  \
   Pyy            0.004692  0.027680  0.097813  0.087056  0.047301 -0.030007
   Iapp           0.000868  0.022276  0.009105  0.026903 -0.047000  0.028216
   Chgb          -0.018321  0.022598 -0.000950  0.069947 -0.060338  0.058838
   Rbp4          -0.054190  0.009149 -0.002459  0.022085  0.041763  0.016814
   Spp1           0.051591  0.111564  0.016615  0.112232  0.079130  0.062653
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.068221 -0.003380  0.078226  0.032785  1.000000 -0.026429
   Hes6          -0.020320  0.166625  0.092192  0.146757 -0.026429  1.000000
   Serpinh1      -0.013161  0.057482  0.097896  0.107891 -0.018198  0.066435
   Npy           -0.019105 -0.037603 -0.045727 -0.001244 -0.017287 -0.027816
   1110012L19Rik -0.021200  0.087427  0.014997  0.049036  0.003337  0.124895

                  Serpinh1       Npy  1110012L19Rik
   Pyy            0.038895 -0.049184      -0.016626
   Iapp          -0.098719  0.103004      -0.111322
   Chgb           0.133066 -0.001308      -0.029256
   Rbp4          -0.015862 -0.015502       0.020484
   Spp1           0.080068 -0.005254       0.035398
   ...                 ...       ...            ...
   Ffar2         -0.018198 -0.017287       0.003337
   Hes6           0.066435 -0.027816       0.124895
   Serpinh1       1.000000 -0.045378       0.015251
   Npy           -0.045378  1.000000      -0.074441
   1110012L19Rik  0.015251 -0.074441       1.000000

   [100 rows x 100 columns],
   'cell_type[T.Pre-endocrine]':                     Pyy      Iapp      Chgb      Rbp4      Spp1      Chga  \
   Pyy            1.000000  0.020670 -0.379718  0.359375  0.076484 -0.205821
   Iapp           0.020670  1.000000 -0.036504 -0.050220 -0.004508 -0.042434
   Chgb          -0.379718 -0.036504  1.000000 -0.315638 -0.025152  0.246978
   Rbp4           0.359375 -0.050220 -0.315638  1.000000 -0.004724 -0.189386
   Spp1           0.076484 -0.004508 -0.025152 -0.004724  1.000000 -0.034309
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2         -0.118500 -0.011122  0.201925 -0.108856 -0.023279  0.042404
   Hes6           0.011250  0.000418  0.141347 -0.010773  0.029990  0.116955
   Serpinh1       0.071297 -0.100755 -0.028425  0.097276 -0.066581  0.082118
   Npy           -0.027846 -0.004826  0.063798 -0.019481 -0.060511  0.013821
   1110012L19Rik -0.017837 -0.007639  0.050765  0.070667  0.093194  0.076656

                       Cck      Ins1      Nnat      Ins2  ...    Nkx6-1  \
   Pyy            0.082662  0.022268 -0.105727  0.024740  ... -0.293398
   Iapp           0.032138  0.070254 -0.033297  0.110201  ... -0.003522
   Chgb           0.045246 -0.044386  0.073433 -0.026498  ...  0.472355
   Rbp4           0.119791  0.090995 -0.033820  0.046261  ... -0.294282
   Spp1           0.013629 -0.012440  0.084041  0.001004  ...  0.037268
   ...                 ...       ...       ...       ...  ...       ...
   Ffar2          0.016331  0.009111  0.022244 -0.082131  ...  0.092398
   Hes6          -0.021109 -0.028082  0.094126 -0.015118  ...  0.074801
   Serpinh1      -0.065988  0.032496  0.057848 -0.032789  ...  0.006738
   Npy           -0.056229 -0.002608  0.052350  0.017977  ...  0.069693
   1110012L19Rik  0.093687 -0.075423  0.063673 -0.002067  ...  0.069697

                     Fxyd3       Hn1   Smarcd2     Pdia6     Ffar2      Hes6  \
   Pyy            0.085773  0.014208  0.004760  0.013450 -0.118500  0.011250
   Iapp           0.067916  0.049780  0.029583 -0.031939 -0.011122  0.000418
   Chgb           0.075265  0.014070  0.043818  0.028925  0.201925  0.141347
   Rbp4           0.095606 -0.002381 -0.002169  0.039275 -0.108856 -0.010773
   Spp1           0.009607  0.050792 -0.039675  0.099767 -0.023279  0.029990
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.140887 -0.027066  0.015476  0.077366  1.000000  0.060714
   Hes6           0.075749  0.021030  0.092567  0.023546  0.060714  1.000000
   Serpinh1       0.010457  0.078384 -0.074242  0.072488 -0.060156  0.019748
   Npy           -0.021975 -0.021114  0.011921 -0.020108  0.076457  0.004585
   1110012L19Rik  0.116808  0.070737  0.063660 -0.003598  0.017237  0.014055

                  Serpinh1       Npy  1110012L19Rik
   Pyy            0.071297 -0.027846      -0.017837
   Iapp          -0.100755 -0.004826      -0.007639
   Chgb          -0.028425  0.063798       0.050765
   Rbp4           0.097276 -0.019481       0.070667
   Spp1          -0.066581 -0.060511       0.093194
   ...                 ...       ...            ...
   Ffar2         -0.060156  0.076457       0.017237
   Hes6           0.019748  0.004585       0.014055
   Serpinh1       1.000000 -0.052088       0.040715
   Npy           -0.052088  1.000000      -0.050140
   1110012L19Rik  0.040715 -0.050140       1.000000

   [100 rows x 100 columns],
   'cell_type[T.Beta]':                     Pyy      Iapp      Chgb      Rbp4      Spp1      Chga  \
   Pyy            1.000000  0.149511 -0.060969  0.262549  0.000923  0.064237
   Iapp           0.149511  1.000000 -0.059670  0.178600  0.015410  0.072456
   Chgb          -0.060969 -0.059670  1.000000 -0.024142 -0.012914  0.247464
   Rbp4           0.262549  0.178600 -0.024142  1.000000  0.020559  0.137727
   Spp1           0.000923  0.015410 -0.012914  0.020559  1.000000  0.027908
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.121288  0.060162  0.102800  0.042472 -0.043413  0.091655
   Hes6           0.023608  0.121431  0.109669  0.042563  0.023859  0.053607
   Serpinh1       0.050504  0.031192  0.046457  0.003655 -0.034180  0.089126
   Npy           -0.085466  0.030286 -0.028382  0.040895  0.103372 -0.043697
   1110012L19Rik  0.015062  0.121291 -0.003616  0.084256  0.007092  0.019781

                       Cck      Ins1      Nnat      Ins2  ...    Nkx6-1  \
   Pyy            0.201032 -0.006533 -0.051147 -0.068713  ... -0.058484
   Iapp           0.237533  0.126759  0.106169  0.018675  ...  0.088066
   Chgb           0.188255 -0.070868  0.054978  0.082236  ...  0.139099
   Rbp4           0.212662 -0.059563  0.151603 -0.039172  ... -0.030196
   Spp1           0.011824  0.057509  0.061604  0.045212  ...  0.067235
   ...                 ...       ...       ...       ...  ...       ...
   Ffar2          0.071039  0.035285  0.073478  0.132138  ...  0.103725
   Hes6           0.073792  0.049478  0.033519  0.046569  ...  0.122185
   Serpinh1       0.033825  0.103040  0.027725  0.089800  ...  0.032381
   Npy            0.119478  0.085757  0.142896  0.101852  ... -0.000521
   1110012L19Rik  0.115989  0.082411  0.010238  0.094493  ...  0.046946

                     Fxyd3       Hn1   Smarcd2     Pdia6     Ffar2      Hes6  \
   Pyy            0.015291  0.059536 -0.022450  0.039212  0.121288  0.023608
   Iapp           0.105386  0.135529  0.029572 -0.026349  0.060162  0.121431
   Chgb           0.174820  0.104280 -0.011348  0.202212  0.102800  0.109669
   Rbp4           0.229523  0.145321  0.002622  0.222834  0.042472  0.042563
   Spp1          -0.008425 -0.012870  0.038438 -0.023911 -0.043413  0.023859
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.045342  0.049527  0.031304  0.127158  1.000000  0.000779
   Hes6           0.072471  0.155919  0.087623  0.042648  0.000779  1.000000
   Serpinh1       0.037157  0.138249  0.183312  0.102287  0.062956  0.119091
   Npy           -0.007501  0.022885  0.026433 -0.038163 -0.013101  0.002770
   1110012L19Rik  0.022938  0.027696  0.051076  0.069832  0.059115  0.127199

                  Serpinh1       Npy  1110012L19Rik
   Pyy            0.050504 -0.085466       0.015062
   Iapp           0.031192  0.030286       0.121291
   Chgb           0.046457 -0.028382      -0.003616
   Rbp4           0.003655  0.040895       0.084256
   Spp1          -0.034180  0.103372       0.007092
   ...                 ...       ...            ...
   Ffar2          0.062956 -0.013101       0.059115
   Hes6           0.119091  0.002770       0.127199
   Serpinh1       1.000000  0.111603       0.040639
   Npy            0.111603  1.000000       0.010919
   1110012L19Rik  0.040639  0.010919       1.000000

   [100 rows x 100 columns]}},
 AnnData object with n_obs × n_vars = 2087 × 100
     obs: 'clusters_coarse', 'clusters', 'S_score', 'G2M_score', 'cell_type', 'sizeFactor', 'pseudotime'
     var: 'highly_variable_genes')

Here is an example where we use a Gaussian on log transformed data.

In [8]:
import numpy as np
from copy import deepcopy

formulas = {
    "mean": [{"variable": "pseudotime", "transform": {"type": "spline", "df": 8}}],
    "sdev": [{"variable": "pseudotime", "transform": {"type": "spline", "df": 3}}],
    "copula": [{"variable": "cell_type"}]
}

example_sce_transform = deepcopy(example_sce)
example_sce_transform.X = np.log1p(example_sce_transform.X)
state = {"template": example_sce_transform, "family": "Gaussian", "formulas": formulas, "n_cells": 2000}
generate_data(state)

Epoch 25/25, Loss: 1.4900, Val Loss: 1.4865

Estimating copula correlation: 100%|██████████| 3/3 [00:00<00:00, 67.17it/s]

({'marginal': {'mean':                               Pyy      Iapp      Chgb      Rbp4      Spp1  \
   Intercept                0.212969  0.210547  0.214014  0.212424  0.218284
   bs(pseudotime, df=8)[1]  0.183440  0.091343 -0.142998  0.166336  0.229393
   bs(pseudotime, df=8)[2]  0.165389  0.073122 -0.093624  0.073957  0.224984
   bs(pseudotime, df=8)[3]  0.164250  0.021182  0.180529  0.072117  0.202226
   bs(pseudotime, df=8)[4]  0.201119  0.091104  0.215213  0.203539  0.033821
   bs(pseudotime, df=8)[5]  0.215041  0.206698  0.216888  0.216143  0.002433
   bs(pseudotime, df=8)[6]  0.216660  0.216910  0.216160  0.216909 -0.015082
   bs(pseudotime, df=8)[7]  0.217459  0.218656  0.215445  0.217220  0.035787
   bs(pseudotime, df=8)[8]  0.218359  0.219639  0.216191  0.218320  0.115469

                                Chga       Cck      Ins1      Nnat      Ins2  \
   Intercept                0.213894  0.214254  0.203226  0.206428  0.211410
   bs(pseudotime, df=8)[1] -0.192917 -0.040444  0.002622 -0.037917 -0.210152
   bs(pseudotime, df=8)[2] -0.071691  0.212674 -0.060562  0.084439 -0.166764
   bs(pseudotime, df=8)[3]  0.194154  0.219401 -0.068838  0.159103 -0.170782
   bs(pseudotime, df=8)[4]  0.215569  0.218618 -0.087151  0.158339 -0.206568
   bs(pseudotime, df=8)[5]  0.216938  0.212559  0.069480  0.189880  0.026235
   bs(pseudotime, df=8)[6]  0.215946  0.204811  0.204848  0.214759  0.209723
   bs(pseudotime, df=8)[7]  0.215901  0.200327  0.220012  0.218874  0.222284
   bs(pseudotime, df=8)[8]  0.216580  0.201200  0.221436  0.220104  0.222527

                            ...    Nkx6-1     Fxyd3       Hn1   Smarcd2  \
   Intercept                ...  0.216568  0.230686  0.220407  0.230486
   bs(pseudotime, df=8)[1]  ...  0.215264  0.200223  0.225105  0.230344
   bs(pseudotime, df=8)[2]  ...  0.215826  0.211480  0.222184  0.238806
   bs(pseudotime, df=8)[3]  ...  0.218349  0.230866  0.221142  0.241089
   bs(pseudotime, df=8)[4]  ...  0.216700  0.236122  0.218984  0.237250
   bs(pseudotime, df=8)[5]  ...  0.214378  0.235732  0.212196  0.199703
   bs(pseudotime, df=8)[6]  ...  0.214949  0.234256  0.214948  0.136206
   bs(pseudotime, df=8)[7]  ...  0.216751  0.228160  0.221172  0.093842
   bs(pseudotime, df=8)[8]  ...  0.219002  0.216481  0.224539  0.056857

                               Pdia6     Ffar2      Hes6  Serpinh1       Npy  \
   Intercept                0.221034  0.233528  0.222969  0.225115  0.216050
   bs(pseudotime, df=8)[1]  0.230502  0.207847  0.224086  0.236101 -0.253713
   bs(pseudotime, df=8)[2]  0.226341  0.223915  0.227021  0.233627 -0.205073
   bs(pseudotime, df=8)[3]  0.218299  0.230896  0.226268  0.231965 -0.207660
   bs(pseudotime, df=8)[4]  0.202030  0.239911  0.223122  0.219222 -0.198365
   bs(pseudotime, df=8)[5]  0.210625  0.239331  0.213929  0.152864 -0.236245
   bs(pseudotime, df=8)[6]  0.219842  0.235888  0.217578  0.149413 -0.129514
   bs(pseudotime, df=8)[7]  0.222243  0.229844  0.220208  0.174861  0.225722
   bs(pseudotime, df=8)[8]  0.222406  0.218953  0.217618  0.204718  0.243238

                            1110012L19Rik
   Intercept                     0.231258
   bs(pseudotime, df=8)[1]       0.165445
   bs(pseudotime, df=8)[2]       0.214330
   bs(pseudotime, df=8)[3]       0.242789
   bs(pseudotime, df=8)[4]       0.249019
   bs(pseudotime, df=8)[5]       0.233383
   bs(pseudotime, df=8)[6]       0.167515
   bs(pseudotime, df=8)[7]       0.116019
   bs(pseudotime, df=8)[8]       0.083004

   [9 rows x 100 columns],
   'sdev':                               Pyy      Iapp      Chgb      Rbp4      Spp1  \
   Intercept                0.205141  0.203612  0.200525  0.197136  0.212426
   bs(pseudotime, df=3)[1]  0.178853 -0.285714  0.197041  0.141109  0.200248
   bs(pseudotime, df=3)[2]  0.206756  0.197507  0.205765  0.200608 -0.260888
   bs(pseudotime, df=3)[3]  0.211413  0.213322  0.205267  0.207467 -0.250492

                                Chga       Cck      Ins1      Nnat      Ins2  \
   Intercept                0.193469  0.195356  0.180174  0.178305  0.158603
   bs(pseudotime, df=3)[1]  0.185765  0.204711 -0.251288 -0.265443 -0.250997
   bs(pseudotime, df=3)[2]  0.200563  0.199060 -0.132246  0.141799 -0.166323
   bs(pseudotime, df=3)[3]  0.202037  0.158243  0.213397  0.208823  0.212133

                            ...    Nkx6-1     Fxyd3       Hn1   Smarcd2  \
   Intercept                ...  0.114097 -0.125137  0.139505 -0.112553
   bs(pseudotime, df=3)[1]  ...  0.110095 -0.007235  0.172959  0.188720
   bs(pseudotime, df=3)[2]  ...  0.127946  0.099593  0.085914 -0.228855
   bs(pseudotime, df=3)[3]  ...  0.154204 -0.118001 -0.201185 -0.250895

                               Pdia6     Ffar2      Hes6  Serpinh1       Npy  \
   Intercept                0.104474 -0.158763  0.049412 -0.010720 -0.243694
   bs(pseudotime, df=3)[1] -0.212185  0.014614  0.160921  0.101983 -0.248222
   bs(pseudotime, df=3)[2] -0.088272  0.124276 -0.054760 -0.269530 -0.247909
   bs(pseudotime, df=3)[3]  0.185312 -0.208038 -0.276406 -0.254586  0.179542

                            1110012L19Rik
   Intercept                    -0.253363
   bs(pseudotime, df=3)[1]       0.208732
   bs(pseudotime, df=3)[2]      -0.158887
   bs(pseudotime, df=3)[3]      -0.244309

   [4 rows x 100 columns]},
  'copula': {'Intercept':                     Pyy      Iapp      Chgb      Rbp4      Spp1      Chga  \
   Pyy            1.000000  0.659306  0.350563  0.769182 -0.309543  0.438936
   Iapp           0.659306  1.000000  0.299147  0.671882 -0.265990  0.356220
   Chgb           0.350563  0.299147  1.000000  0.515691 -0.457856  0.746928
   Rbp4           0.769182  0.671882  0.515691  1.000000 -0.376667  0.569311
   Spp1          -0.309543 -0.265990 -0.457856 -0.376667  1.000000 -0.511902
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2         -0.050993 -0.140291  0.238861 -0.027738 -0.236956  0.201118
   Hes6          -0.288027 -0.232894 -0.307868 -0.374609  0.038108 -0.325835
   Serpinh1      -0.396775 -0.346189 -0.574672 -0.506196  0.541569 -0.581739
   Npy            0.107208  0.322543  0.040739  0.118725 -0.086230  0.081370
   1110012L19Rik -0.217722 -0.230462 -0.005952 -0.218349 -0.179190  0.039283

                       Cck      Ins1      Nnat      Ins2  ...    Nkx6-1  \
   Pyy           -0.203445  0.370009  0.518693  0.420944  ...  0.056573
   Iapp          -0.252468  0.707726  0.814110  0.782277  ...  0.213332
   Chgb          -0.023968  0.111458  0.238807  0.144764  ...  0.251689
   Rbp4          -0.245029  0.370983  0.554000  0.426446  ...  0.091510
   Spp1          -0.463665 -0.154494 -0.231182 -0.177856  ... -0.285635
   ...                 ...       ...       ...       ...  ...       ...
   Ffar2          0.232787 -0.134891 -0.124040 -0.133369  ...  0.077302
   Hes6           0.233046 -0.157533 -0.188601 -0.161252  ...  0.043662
   Serpinh1      -0.063444 -0.171703 -0.272909 -0.184731  ... -0.133334
   Npy           -0.040114  0.507250  0.382559  0.476538  ...  0.123698
   1110012L19Rik  0.403471 -0.135212 -0.162389 -0.138393  ...  0.104418

                     Fxyd3       Hn1   Smarcd2     Pdia6     Ffar2      Hes6  \
   Pyy            0.043505 -0.327595 -0.425213  0.292438 -0.050993 -0.288027
   Iapp          -0.042725 -0.254002 -0.369932  0.486220 -0.140291 -0.232894
   Chgb           0.202256 -0.421869 -0.447081 -0.031141  0.238861 -0.307868
   Rbp4           0.088393 -0.425495 -0.524885  0.284716 -0.027738 -0.374609
   Spp1          -0.255144  0.129661  0.069049  0.215044 -0.236956  0.038108
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.201921 -0.026231  0.050995 -0.177690  1.000000  0.040057
   Hes6           0.001689  0.397548  0.462175 -0.057881  0.040057  1.000000
   Serpinh1      -0.143984  0.393509  0.390353  0.115850 -0.165725  0.324708
   Npy           -0.081399 -0.063184 -0.073761  0.204100 -0.090319 -0.078008
   1110012L19Rik  0.209419  0.163430  0.201545 -0.246450  0.167353  0.151104

                  Serpinh1       Npy  1110012L19Rik
   Pyy           -0.396775  0.107208      -0.217722
   Iapp          -0.346189  0.322543      -0.230462
   Chgb          -0.574672  0.040739      -0.005952
   Rbp4          -0.506196  0.118725      -0.218349
   Spp1           0.541569 -0.086230      -0.179190
   ...                 ...       ...            ...
   Ffar2         -0.165725 -0.090319       0.167353
   Hes6           0.324708 -0.078008       0.151104
   Serpinh1       1.000000 -0.057708       0.013296
   Npy           -0.057708  1.000000      -0.053252
   1110012L19Rik  0.013296 -0.053252       1.000000

   [100 rows x 100 columns],
   'cell_type[T.Ngn3 high EP]':                     Pyy      Iapp      Chgb      Rbp4      Spp1      Chga  \
   Pyy            1.000000  0.024902  0.054098  0.081265  0.073525  0.010506
   Iapp           0.024902  1.000000  0.054541  0.017816  0.056056 -0.011130
   Chgb           0.054098  0.054541  1.000000  0.024797 -0.024257  0.266718
   Rbp4           0.081265  0.017816  0.024797  1.000000  0.094295 -0.000291
   Spp1           0.073525  0.056056 -0.024257  0.094295  1.000000 -0.144409
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.006293 -0.069946  0.064212  0.023816 -0.115723  0.058815
   Hes6          -0.030224  0.052755 -0.093508  0.021881 -0.069662 -0.135312
   Serpinh1       0.023044 -0.044149 -0.068580  0.034166  0.297738 -0.218477
   Npy            0.023745  0.192714  0.118404  0.030071  0.066545  0.030158
   1110012L19Rik -0.040528 -0.052658  0.101477 -0.047035 -0.393936  0.183067

                       Cck      Ins1      Nnat      Ins2  ...    Nkx6-1  \
   Pyy            0.004864 -0.032657  0.077291  0.019907  ... -0.013715
   Iapp          -0.040569  0.083397  0.061791  0.136101  ... -0.031814
   Chgb           0.096077  0.044847  0.022638  0.073961  ...  0.042952
   Rbp4          -0.053989  0.021043  0.015100  0.018287  ... -0.041984
   Spp1          -0.707018 -0.000796 -0.067447 -0.008150  ... -0.407018
   ...                 ...       ...       ...       ...  ...       ...
   Ffar2          0.125652  0.038359 -0.041944 -0.019707  ...  0.053547
   Hes6           0.060436  0.003105  0.069245  0.024557  ...  0.092611
   Serpinh1      -0.284273 -0.006091 -0.006052 -0.052510  ... -0.086168
   Npy           -0.060498  0.173972  0.002178  0.174471  ... -0.076129
   1110012L19Rik  0.378277 -0.038311  0.061590  0.012746  ...  0.213297

                     Fxyd3       Hn1   Smarcd2     Pdia6     Ffar2      Hes6  \
   Pyy           -0.014385  0.020788  0.064292  0.128053  0.006293 -0.030224
   Iapp           0.000699  0.011393 -0.036701  0.075563 -0.069946  0.052755
   Chgb           0.114036 -0.059047 -0.108079 -0.075554  0.064212 -0.093508
   Rbp4          -0.003751 -0.085788 -0.027719  0.050103  0.023816  0.021881
   Spp1          -0.317825 -0.385025 -0.295403  0.380538 -0.115723 -0.069662
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.149480  0.051105  0.087258 -0.020598  1.000000 -0.036450
   Hes6          -0.039203  0.263745  0.265872  0.127414 -0.036450  1.000000
   Serpinh1      -0.191713 -0.025801  0.054348  0.271064 -0.124485  0.137831
   Npy           -0.082505 -0.085604 -0.163015  0.036806 -0.034459 -0.043678
   1110012L19Rik  0.235713  0.198349  0.060345 -0.162409  0.075131  0.044211

                  Serpinh1       Npy  1110012L19Rik
   Pyy            0.023044  0.023745      -0.040528
   Iapp          -0.044149  0.192714      -0.052658
   Chgb          -0.068580  0.118404       0.101477
   Rbp4           0.034166  0.030071      -0.047035
   Spp1           0.297738  0.066545      -0.393936
   ...                 ...       ...            ...
   Ffar2         -0.124485 -0.034459       0.075131
   Hes6           0.137831 -0.043678       0.044211
   Serpinh1       1.000000  0.016517      -0.185751
   Npy            0.016517  1.000000      -0.017235
   1110012L19Rik -0.185751 -0.017235       1.000000

   [100 rows x 100 columns],
   'cell_type[T.Pre-endocrine]':                     Pyy      Iapp      Chgb      Rbp4      Spp1      Chga  \
   Pyy            1.000000  0.199346 -0.271707  0.559085  0.070719 -0.117458
   Iapp           0.199346  1.000000 -0.009147  0.160149 -0.002999 -0.011397
   Chgb          -0.271707 -0.009147  1.000000 -0.048763 -0.028347  0.414268
   Rbp4           0.559085  0.160149 -0.048763  1.000000  0.055046 -0.016017
   Spp1           0.070719 -0.002999 -0.028347  0.055046  1.000000 -0.009553
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2         -0.170728 -0.040035  0.214534 -0.170231 -0.028830  0.091981
   Hes6          -0.127905 -0.056230 -0.007201 -0.247625 -0.097636  0.037130
   Serpinh1      -0.009902 -0.070669 -0.224649 -0.123313 -0.028425 -0.035220
   Npy            0.019545 -0.013820  0.037336  0.044399 -0.022602  0.046537
   1110012L19Rik -0.161705 -0.083870 -0.027311 -0.224923  0.081078  0.056530

                       Cck      Ins1      Nnat      Ins2  ...    Nkx6-1  \
   Pyy           -0.189494 -0.071705 -0.098173 -0.152909  ... -0.308118
   Iapp          -0.102923  0.105023 -0.058426  0.114103  ... -0.039048
   Chgb          -0.185635 -0.095108  0.003825 -0.105037  ...  0.425051
   Rbp4          -0.332695 -0.060862 -0.072233 -0.210703  ... -0.279222
   Spp1          -0.028371 -0.039859  0.028824 -0.072843  ...  0.002927
   ...                 ...       ...       ...       ...  ...       ...
   Ffar2          0.086910 -0.022113  0.003861  0.006349  ...  0.113053
   Hes6           0.154654  0.046087  0.088162  0.184329  ...  0.095532
   Serpinh1       0.145219  0.030491  0.014734  0.062331  ...  0.010580
   Npy           -0.012086  0.065979 -0.050235  0.080129  ...  0.028052
   1110012L19Rik  0.298432 -0.027001  0.120719  0.176679  ...  0.128634

                     Fxyd3       Hn1   Smarcd2     Pdia6     Ffar2      Hes6  \
   Pyy            0.058837 -0.156064 -0.166826  0.071487 -0.170728 -0.127905
   Iapp           0.024795 -0.074168 -0.043457 -0.031689 -0.040035 -0.056230
   Chgb           0.044953 -0.208225 -0.178103  0.027963  0.214534 -0.007201
   Rbp4           0.009635 -0.301220 -0.325303  0.128981 -0.170231 -0.247625
   Spp1           0.006223  0.007395 -0.086794  0.107347 -0.028830 -0.097636
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.146648 -0.001165  0.039700  0.013060  1.000000  0.098057
   Hes6           0.092385  0.178180  0.239392 -0.046207  0.098057  1.000000
   Serpinh1       0.056834  0.226685  0.129270  0.078157 -0.067773  0.145198
   Npy           -0.000323 -0.094865  0.011816  0.000165 -0.078049 -0.019983
   1110012L19Rik  0.190922  0.194515  0.221934 -0.101980  0.088386  0.156576

                  Serpinh1       Npy  1110012L19Rik
   Pyy           -0.009902  0.019545      -0.161705
   Iapp          -0.070669 -0.013820      -0.083870
   Chgb          -0.224649  0.037336      -0.027311
   Rbp4          -0.123313  0.044399      -0.224923
   Spp1          -0.028425 -0.022602       0.081078
   ...                 ...       ...            ...
   Ffar2         -0.067773 -0.078049       0.088386
   Hes6           0.145198 -0.019983       0.156576
   Serpinh1       1.000000 -0.055259       0.113444
   Npy           -0.055259  1.000000       0.004983
   1110012L19Rik  0.113444  0.004983       1.000000

   [100 rows x 100 columns],
   'cell_type[T.Beta]':                     Pyy      Iapp      Chgb      Rbp4      Spp1      Chga  \
   Pyy            1.000000  0.200553 -0.087054  0.272856  0.005015  0.038562
   Iapp           0.200553  1.000000 -0.351755  0.158900  0.029604 -0.151396
   Chgb          -0.087054 -0.351755  1.000000 -0.041707 -0.049602  0.303137
   Rbp4           0.272856  0.158900 -0.041707  1.000000 -0.000996  0.123035
   Spp1           0.005015  0.029604 -0.049602 -0.000996  1.000000 -0.007176
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.086533 -0.162555  0.194071  0.046345 -0.023311  0.147262
   Hes6           0.041405 -0.002184  0.105755  0.037000  0.055210  0.043470
   Serpinh1       0.049829  0.047829  0.014600  0.045933 -0.019805  0.055839
   Npy           -0.097232  0.305977 -0.199103 -0.155171  0.079667 -0.086123
   1110012L19Rik  0.007291  0.077417 -0.003060  0.105886  0.055965  0.047172

                       Cck      Ins1      Nnat      Ins2  ...    Nkx6-1  \
   Pyy            0.186308  0.015661  0.071798  0.033934  ... -0.049346
   Iapp           0.063001  0.643260  0.721868  0.711261  ...  0.257853
   Chgb           0.177205 -0.353866 -0.291398 -0.316785  ...  0.011223
   Rbp4           0.165160 -0.075362  0.138050 -0.014092  ... -0.035542
   Spp1          -0.058576  0.042922  0.064253  0.060986  ...  0.108268
   ...                 ...       ...       ...       ...  ...       ...
   Ffar2          0.073667 -0.174929 -0.123297 -0.153754  ...  0.022300
   Hes6           0.115351 -0.059634 -0.054677 -0.069908  ...  0.100064
   Serpinh1       0.032322  0.096337  0.057568  0.131554  ...  0.073019
   Npy            0.010009  0.496939  0.404667  0.459690  ...  0.177522
   1110012L19Rik  0.127891  0.056437  0.049438  0.067249  ...  0.091379

                     Fxyd3       Hn1   Smarcd2     Pdia6     Ffar2      Hes6  \
   Pyy            0.017281  0.074396 -0.019339  0.088612  0.086533  0.041405
   Iapp          -0.086122  0.100847  0.023230  0.528207 -0.162555 -0.002184
   Chgb           0.236241  0.063774 -0.012290 -0.118498  0.194071  0.105755
   Rbp4           0.252819  0.123247  0.013251  0.146110  0.046345  0.037000
   Spp1          -0.035716  0.012046  0.025731 -0.024397 -0.023311  0.055210
   ...                 ...       ...       ...       ...       ...       ...
   Ffar2          0.104804  0.031209  0.067549 -0.045996  1.000000  0.059371
   Hes6           0.075780  0.142448  0.123675 -0.019924  0.059371  1.000000
   Serpinh1       0.052317  0.136620  0.145847  0.125513  0.038464  0.116155
   Npy           -0.148268  0.018048  0.040080  0.282590 -0.157163 -0.072658
   1110012L19Rik  0.071816  0.089861  0.080593  0.066031  0.080042  0.154654

                  Serpinh1       Npy  1110012L19Rik
   Pyy            0.049829 -0.097232       0.007291
   Iapp           0.047829  0.305977       0.077417
   Chgb           0.014600 -0.199103      -0.003060
   Rbp4           0.045933 -0.155171       0.105886
   Spp1          -0.019805  0.079667       0.055965
   ...                 ...       ...            ...
   Ffar2          0.038464 -0.157163       0.080042
   Hes6           0.116155 -0.072658       0.154654
   Serpinh1       1.000000  0.119661       0.099432
   Npy            0.119661  1.000000      -0.008787
   1110012L19Rik  0.099432 -0.008787       1.000000

   [100 rows x 100 columns]}},
 AnnData object with n_obs × n_vars = 2000 × 100
     obs: 'clusters_coarse', 'clusters', 'S_score', 'G2M_score', 'cell_type', 'sizeFactor', 'pseudotime'
     var: 'highly_variable_genes')